# Send builds to container-based infrastructure
# http://docs.travis-ci.com/user/workers/container-based-infrastructure/
sudo: false
language: ruby
cache:
  - bundler
rvm:
  - 2.1.10
  - 2.2.8
  # Since the Travis Build Env does not recognize `2.3` alias yet
  # We need to specify the version precisely
  - 2.3.6
  - 2.4.3
  - 2.5.0
  - ruby-head
before_install:
# Need to install something extra to test JS
- npm install
gemfile:
  - gemfiles/i18n_0_6.gemfile
  - gemfiles/i18n_0_7.gemfile
  - gemfiles/i18n_0_8.gemfile
  - gemfiles/i18n_0_9.gemfile
matrix:
  fast_finish: true
  allow_failures:
    - rvm: ruby-head
